### ISSUE TITLE
NPM version is ancient

### ISSUE THREAD

**Issue by domoritz** [vega/compassql#424]
```
var vlTree = cql.result.mapLeaves(result, function(item) {
                        ^

TypeError: Cannot read property 'mapLeaves' of undefined
    at Object.<anonymous> (/Users/domoritz/Developer/UW/draco/data/generate.js:32:25)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by domoritz** [comment]
<img width="831" alt="screen shot 2017-11-30 at 20 37 27" src="https://user-images.githubusercontent.com/589034/33451129-510fbb84-d60e-11e7-9f27-c4ba6e41acb9.png">

**Comment by domoritz** [comment]
I found that the problem is that the version on NPM is ancient.
